### ISSUE TITLE
Add ajax loaded options

### ISSUE THREAD

**Issue by AlesJiranek** [AlesJiranek/autocomplete-choice-input#1]
It would be great if input could load it`s options asynchronously

**Comment by bhagatparwinder** [comment]
I can do this. Can you assign this issue to me @AlesJiranek Thanks!

**Comment by bhagatparwinder** [comment]
If you are unable to assign it to me (because I'm not a contributor on the project, yet), you can add the tag already assigned @AlesJiranek

**Comment by AlesJiranek** [comment]
@bhagatparwinder thanks

**Comment by bhagatparwinder** [comment]
✅  Please check https://github.com/AlesJiranek/autocomplete-choice-input/pull/2

Let me know if there are concerns/comments.

**Comment by bhagatparwinder** [comment]
Updated pull
