### ISSUE TITLE
Allow loading suggestions remotely via ajax

### ISSUE THREAD

**Issue by AlesJiranek** [AlesJiranek/autocomplete-choice-input#3]
Currently it is possible to load all options via ajax on initialisation. 
It would be great to have an option to load suggestions on the fly while typing.

**Comment by mdew192837** [comment]
Do you have any guidance on how to do this? @AlesJiranek

**Comment by AlesJiranek** [comment]
I was thinking about some flag that coopartes with endpoint option which says, that component will not load all options during initialisation, but it will request some endpoint in `suggestItems` function
